### PR TITLE
upgrade jenkins slave to 1.1.0

### PR DESCRIPTION
**Pull request by pydevops**

### CODE REVIEW

**Comment by pydevops** [comment]
test this please

**Comment by pydevops** [comment]
test this please

**Comment by chrislovecnm** [comment]
@pydevops before we merge this, I would like to know what the cause of the test failures are.

Thanks

**Comment by pydevops** [comment]
@chrislovecnm 
https://ci.gflocks.com/job/gke-networking-demos/21/console shows the gcloud.deployment-manager.deployments.delete timed out  (maybe not directly related: there was in networking issue in us-central1-c: https://status.cloud.google.com/incident/cloud-networking/18016) 
https://ci.gflocks.com/job/gke-networking-demos/22/console shows `network1-deployment` exists. no cleanup has been done on the gcloud deployment. I have to clean up routes, network/subnet etc. manually in build 21 but missed the deployment manager.

**Review by chrislovecnm — APPROVED** [review]

**Pull request merged**
