### PR TITLE
Reduced the required service backends

### PR DESCRIPTION
**Pull request by emailbob**
- Reduced the required service backends from 10 to 8
- Updated valdiate-pod-to-service-communication.sh kubectl commands with field-selector and jsonpaths instead of grep and awk
- Replaced references to grep and awk with native gcloud and kubectl filter and format commands. I think I had an instnace in which the formatting for the "compute addresses list" command moved so the print{$3} grabbed zone instead of the ip.
- replaced kubectl create command with apply to make it more idempotent
- Added more pod to service validation checks

### CODE REVIEW

**Comment by chrislovecnm** [comment]
> Reduced the required service backends from 10 to 8

What is the default quota?  Do we know were these backend services are coming from?

**Comment by emailbob** [comment]
> > Reduced the required service backends from 10 to 8
> 
> What is the default quota? Do we know were these backend services are coming from?

The default quota when we create projects from our org is 9

We have four cluster and each cluster uses 2 service backends. One is for the ingress and the other is for the internal load balancer

**Review by chrislovecnm — DISMISSED** [review]
Looks great

**Review by chrislovecnm — APPROVED** [review]
Thanks

**Pull request merged**
