### PR TITLE
Bumping version to try 1.12.x

### PR DESCRIPTION
**Pull request by cxhercules**

### CODE REVIEW

**Comment by cxhercules** [comment]
test this please

**Comment by chrislovecnm** [comment]
test this please

**Comment by cxhercules** [comment]
test this please

**Comment by cxhercules** [comment]
test this please

**Comment by cxhercules** [comment]
test this please

**Comment by cxhercules** [comment]
test this please

**Comment by cxhercules** [comment]
test this please

**Review by chrislovecnm — APPROVED** [review]

**Pull request merged**
