### PR TITLE
updated: boilerplate files in test folder, Dockerfile to include curl

### PR DESCRIPTION
**Pull request by Syd-Vigilant**
… version

### CODE REVIEW

**Review by chrislovecnm — APPROVED** [review]

**Comment by chrislovecnm** [comment]
please test this

**Comment by chrislovecnm** [comment]
please test this

**Comment by chrislovecnm** [comment]
Please test this

**Comment by chrislovecnm** [comment]
please test this

**Comment by chrislovecnm** [comment]
test this please

**Review by geojaz — COMMENTED** [review]
@Syd-Vigilant your version of curl is breaking the testing:

```
Status: Downloaded newer image for nginx:alpine
 ---> b411e34b4606
Step 2/2 : RUN apk add --no-cache curl=7.61.1-r1
 ---> Running in a481ffa120be
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
[91mERROR: [0m[91munsatisfiable constraints:[0m[91m
[0m  curl-7.63.0-r0:
    breaks: world[curl=7.61.1-r1]
The command '/bin/sh -c apk add --no-cache curl=7.61.1-r1' returned a non-zero code: 1
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: exit status 1
--------------------------------------------------------------------------------

Makefile:63: recipe for target 'build_container' failed
make: *** [build_container] Error 1
```

Could you please try resubmitting with with 7.63.0-r0 or latest which is 7.64.0?

**Comment by chrislovecnm** [comment]
@geojaz he is no longer with helmsman, we need to update this PR ourselves

**Comment by chrislovecnm** [comment]
Closing, Kristen will assign this to someone

**Pull request closed without merging**
