### PR TITLE
Fixed Qwiklabs readme title

### PR DESCRIPTION
**Pull request by tm-g**

### CODE REVIEW

**Comment by tm-g** [comment]
/assign @chrislovecnm 

Initial build crashed due to a gcloud crash in teardown, but a replay of the build passed. Can this be merged manually? https://ci.gflocks.com/job/gke-networking-demos/6/

**Comment by chrislovecnm** [comment]
This failed CI

**Comment by tm-g** [comment]
> This failed CI

Indeed. However it only failed due to gcloud crashing. I replayed the build (making zero changes at all), and it succeeded on the second try, you can see the replayed build here: https://ci.gflocks.com/job/gke-networking-demos/6/

Is the replayed build success sufficient for merging this? Or do I need to close this PR and file a new one?

**Comment by chrislovecnm** [comment]
Why is gcloud crashing? Do we need to update our Jenkins container?

**Comment by chrislovecnm** [comment]
test this please

**Review by chrislovecnm — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
